openapi: 3.0.0
info:
  version: 1.0.0
  title: Tomtom API common data

components:
  schemas:
    Address:
      type: object
      properties:
        streetNumber:
          type: string
        streetName:
          type: string
        municipality:
          type: string
        neighbourhood:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
        country:
          type: string
        freeformAddress:
          type: string
        localName:
          type: string
      required:
        - streetNumber
        - streetName
        - municipality
        - postalCode
        - countryCode
        - country
        - freeformAddress
        - localName
